Repository 5josama/sb03-monew-team5, pull requests merged in 2025-07, with the labels that each got.

#18 [Feature/article] news view 등록 기능
  src/.DS_Store
  src/main/.DS_Store
  src/main/generated/com/sprint5team/monew/domain/article/entity/QArticle.java
  src/main/generated/com/sprint5team/monew/domain/article/entity/QArticleCount.java
  src/main/generated/com/sprint5team/monew/domain/article/mapper/ArticleViewMapperImpl.java
  src/main/generated/com/sprint5team/monew/domain/comment/entity/QComment.java
  src/main/generated/com/sprint5team/monew/domain/notification/entity/QNotification.java
  src/main/generated/com/sprint5team/monew/domain/user/entity/QUser.java
  src/main/generated/com/sprint5team/monew/domain/user_interest/entity/QUserInterest.java
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleController.java
  src/main/java/com/sprint5team/monew/domain/article/dto/ArticleViewDto.java
  src/main/java/com/sprint5team/monew/domain/article/entity/Article.java
  src/main/java/com/sprint5team/monew/domain/article/entity/ArticleCount.java
  src/main/java/com/sprint5team/monew/domain/article/exception/ArticleNotFoundException.java
  src/main/java/com/sprint5team/monew/domain/article/mapper/ArticleViewMapper.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCountRepository.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleRepository.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleService.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/user_interest/entity/UserInterest.java
  src/main/resources/.DS_Store
  src/main/resources/schema.sql
  src/test/java/com/sprint5team/monew/controller/article/ArticleControllerTest.java
  src/test/java/com/sprint5team/monew/repository/article/ArticleCountRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/article/ArticleServiceTest.java
  src/test/resources/application-test.yaml
  src/test/resources/schema.sql
Labels: New Feature

#29 [Feature/comment] 댓글 등록 기능 구현
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentApi.java
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentController.java
  src/main/java/com/sprint5team/monew/domain/comment/dto/CommentRegisterRequest.java
  src/main/java/com/sprint5team/monew/domain/comment/entity/Comment.java
  src/main/java/com/sprint5team/monew/domain/comment/entity/Like.java
  src/main/java/com/sprint5team/monew/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/sprint5team/monew/domain/comment/mapper/CommentMapper.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/CommentRepository.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/LikeRepository.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentService.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/comment/CommentControllerTest.java
  src/test/java/com/sprint5team/monew/integration/comment/CommentIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/comment/CommentRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
Labels: New Feature

#34 [Feature/article] 뉴스 기사 출처 목록 조회
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleController.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleRepository.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleService.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/article/ArticleControllerTest.java
  src/test/java/com/sprint5team/monew/integration/article/ArticleIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/article/ArticleRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/article/ArticleServiceTest.java
Labels: New Feature

#37 [Feature/notification] 알림 목록 조회 기능
  src/main/java/com/sprint5team/monew/domain/notification/controller/NotificationController.java
  src/main/java/com/sprint5team/monew/domain/notification/dto/CursorPageResponseNotificationDto.java
  src/main/java/com/sprint5team/monew/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationService.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/user/repository/UserRepository.java
  src/main/resources/schema.sql
  src/test/java/com/sprint5team/monew/controller/notification/NotificationControllerTest.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/notification/NotificationRepositoryCustomTest.java
  src/test/java/com/sprint5team/monew/repository/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/notification/NotificationServiceTest.java
  src/test/resources/schema-test.sql
Labels: New Feature

#39 [Refactor/article] 뉴스 기사 목록 조회
  src/main/java/com/sprint5team/monew/domain/article/dto/ArticleCommentCount.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/CommentRepository.java
Labels: Refactor

#46 [Feature/article] 뉴스 기사 논리 삭제
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleController.java
  src/main/java/com/sprint5team/monew/domain/article/entity/Article.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCustomRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleService.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/article/ArticleControllerTest.java
  src/test/java/com/sprint5team/monew/integration/article/ArticleIntegrationTest.java
  src/test/java/com/sprint5team/monew/service/article/ArticleServiceTest.java
Labels: New Feature

#50 [Feature/article] 뉴스 기사 물리 삭제
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleController.java
  src/main/java/com/sprint5team/monew/domain/article/dto/CursorPageFilter.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCountRepository.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCustomRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleService.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/CommentRepository.java
  src/test/java/com/sprint5team/monew/controller/article/ArticleControllerTest.java
  src/test/java/com/sprint5team/monew/integration/article/ArticleIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/article/ArticleRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/article/ArticleServiceTest.java
Labels: New Feature

#49 [Feature/delete interest] 관심사 삭제 기능
  .gitignore
  src/main/java/com/sprint5team/monew/domain/interest/controller/InterestController.java
  src/main/java/com/sprint5team/monew/domain/interest/entity/Interest.java
  src/main/java/com/sprint5team/monew/domain/interest/exception/InterestNotExistException.java
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestService.java
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/interest/InterestControllerTest.java
  src/test/java/com/sprint5team/monew/integration/interest/InterestIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/interest/InterestRepositoryTest.java
  src/test/java/com/sprint5team/monew/repository/keyword/KeywordRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/interest/InterestServiceTest.java
Labels: New Feature

#53 [Feature/comment] 댓글 조회 기능 구현
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentApi.java
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentController.java
  src/main/java/com/sprint5team/monew/domain/comment/dto/CursorPageResponseCommentDto.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/CommentRepository.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentService.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/comment/CommentControllerTest.java
  src/test/java/com/sprint5team/monew/integration/comment/CommentIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/comment/CommentRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
Labels: New Feature

#58 [Feature/notification] 알림 수정 기능
  src/main/java/com/sprint5team/monew/domain/notification/controller/NotificationController.java
  src/main/java/com/sprint5team/monew/domain/notification/entity/Notification.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationService.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/notification/NotificationControllerTest.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/notification/NotificationServiceTest.java
Labels: New Feature

#64 [Feature/actuator] Actuator로 Spring Batch 작업 및 Custom metric 모니터링
  build.gradle
  src/main/java/com/sprint5team/monew/base/aop/MetricAspect.java
  src/main/java/com/sprint5team/monew/base/health/MonewHealthIndicator.java
  src/main/java/com/sprint5team/monew/base/metric/MonewMetrics.java
  src/main/java/com/sprint5team/monew/base/service/BatchStatusService.java
Labels: New Feature

#66 [Feature/comment] 댓글 물리 삭제 기능 구현
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentApi.java
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentController.java
  src/main/java/com/sprint5team/monew/domain/comment/entity/Comment.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentService.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/comment/CommentControllerTest.java
  src/test/java/com/sprint5team/monew/integration/comment/CommentIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/comment/CommentRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
Labels: New Feature, Refactor

#71 [Bugfix/comment] 로컬에서 댓글 조회시 500에러 발생하는 버그 수정
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentController.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/comment/CommentControllerTest.java
  src/test/java/com/sprint5team/monew/integration/comment/CommentIntegrationTest.java
Labels: Bug

#75 [Bugfix/Spring Batch] Spring Batch 메타 테이블 자동 생성
  src/main/java/com/sprint5team/monew/base/config/BatchMetaInitializerConfig.java
  src/main/resources/application.yaml
  src/main/resources/sql/batch-postgresql.sql
Labels: Bug

#67 [Feature/edit interest] 관심사 수정 기능
  README.md
  build.gradle
  src/main/java/com/sprint5team/monew/base/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint5team/monew/domain/interest/controller/InterestController.java
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestService.java
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/keyword/exception/NoKeywordsToUpdateException.java
  src/main/java/com/sprint5team/monew/domain/keyword/repository/KeywordRepository.java
  src/main/java/com/sprint5team/monew/domain/user_interest/repository/UserInterestRepository.java
  src/test/java/com/sprint5team/monew/controller/interest/InterestControllerTest.java
  src/test/java/com/sprint5team/monew/integration/interest/InterestIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/interest/InterestRepositoryExistSimilarNameTest.java
  src/test/java/com/sprint5team/monew/repository/keyword/KeywordRepositoryTest.java
  src/test/java/com/sprint5team/monew/repository/user_interest/UserInterestRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/interest/InterestServiceTest.java
Labels: New Feature

#73 [Feature/notification] 알림 삭제 기능
  src/main/java/com/sprint5team/monew/domain/notification/entity/Notification.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationScheduler.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationServiceImpl.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationIntegrationTest.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationSchedulerIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/notification/NotificationRepositoryTest.java
Labels: New Feature

#80 [Chore/infra] AWS EC2 기반 Spring Boot 배포 인프라 설정
  .gitignore
  Dockerfile
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: Document, Refactor

#77 [Feature/comment] 댓글 정보 수정 기능 구현
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentApi.java
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentController.java
  src/main/java/com/sprint5team/monew/domain/comment/dto/CommentUpdateRequest.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentService.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/comment/CommentControllerTest.java
  src/test/java/com/sprint5team/monew/integration/comment/CommentIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/comment/CommentRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
Labels: New Feature

#91 [Feature/user] 사용자 정보 수정 기능 구현
  src/main/java/com/sprint5team/monew/domain/user/controller/UserController.java
  src/main/java/com/sprint5team/monew/domain/user/dto/UserUpdateRequest.java
  src/main/java/com/sprint5team/monew/domain/user/service/UserService.java
  src/main/java/com/sprint5team/monew/domain/user/service/UserServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/user/UserControllerTest.java
  src/test/java/com/sprint5team/monew/integration/user/UserIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/user/UserRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/user/UserServiceTest.java
Labels: New Feature

#94 [Feature/comment] 댓글 좋아요 기능 추가
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentApi.java
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentController.java
  src/main/java/com/sprint5team/monew/domain/comment/mapper/LikeMapper.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentService.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/comment/CommentControllerTest.java
  src/test/java/com/sprint5team/monew/integration/comment/CommentIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/comment/CommentRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
Labels: New Feature

#96 [Feature/comment] 댓글 좋아요 취소 기능 구현
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentApi.java
  src/main/java/com/sprint5team/monew/domain/comment/controller/CommentController.java
  src/main/java/com/sprint5team/monew/domain/comment/exception/AlreadyLikedException.java
  src/main/java/com/sprint5team/monew/domain/comment/exception/CommentException.java
  src/main/java/com/sprint5team/monew/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/sprint5team/monew/domain/comment/exception/LikeNotFoundException.java
  src/main/java/com/sprint5team/monew/domain/comment/mapper/CommentMapper.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/LikeRepository.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentService.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/comment/CommentControllerTest.java
  src/test/java/com/sprint5team/monew/integration/comment/CommentIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/comment/CommentRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
Labels: New Feature

#106 [Feature/user] 사용자 삭제 기능 구현
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCountRepository.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/CommentRepository.java
  src/main/java/com/sprint5team/monew/domain/comment/repository/LikeRepository.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint5team/monew/domain/user/controller/UserActivityApi.java
  src/main/java/com/sprint5team/monew/domain/user/controller/UserApi.java
  src/main/java/com/sprint5team/monew/domain/user/controller/UserController.java
  src/main/java/com/sprint5team/monew/domain/user/entity/User.java
  src/main/java/com/sprint5team/monew/domain/user/repository/UserRepository.java
  src/main/java/com/sprint5team/monew/domain/user/service/UserService.java
  src/main/java/com/sprint5team/monew/domain/user/service/UserServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/user_interest/repository/UserInterestRepository.java
  src/test/java/com/sprint5team/monew/controller/user/UserControllerTest.java
  src/test/java/com/sprint5team/monew/integration/user/UserIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/user/UserRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/user/UserServiceTest.java
Labels: New Feature

#112 [Refactor/article] 뉴스 기사 백업 기능 개선
  src/main/java/com/sprint5team/monew/base/config/ArticleBackupJobConfig.java
  src/main/java/com/sprint5team/monew/base/service/BatchMetadataService.java
  src/main/java/com/sprint5team/monew/base/util/ArticleScraperTasklet.java
  src/main/java/com/sprint5team/monew/domain/article/dto/ArticleViewDto.java
  src/main/java/com/sprint5team/monew/domain/article/entity/ArticleKeyword.java
  src/main/java/com/sprint5team/monew/domain/article/mapper/ArticleViewMapper.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleRepository.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleBackUpScheduler.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleConsumer.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleQueueManager.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleScraperScheduler.java
  src/main/java/com/sprint5team/monew/domain/article/util/KeywordConsumer.java
  src/main/java/com/sprint5team/monew/domain/article/util/KeywordQueueManager.java
  src/main/java/com/sprint5team/monew/domain/article/util/NaverNewsApiClient.java
  src/main/java/com/sprint5team/monew/domain/keyword/entity/Keyword.java
  src/test/java/com/sprint5team/monew/service/article/ArticleServiceTest.java
Labels: Refactor

#116 [Feature/swagger interest] 관심사 스웨거 추가
  src/main/java/com/sprint5team/monew/domain/interest/controller/InterestApi.java
  src/main/java/com/sprint5team/monew/domain/interest/controller/InterestController.java
  src/main/java/com/sprint5team/monew/domain/interest/mapper/InterestMapper.java
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestService.java
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/user_interest/controller/UserInterestApi.java
  src/main/java/com/sprint5team/monew/domain/user_interest/controller/UserInterestController.java
  src/test/java/com/sprint5team/monew/controller/interest/InterestControllerTest.java
  src/test/java/com/sprint5team/monew/service/interest/InterestServiceTest.java
Labels: New Feature

#121 [Refactor/notification] 알림 전체 리팩터링
  src/main/java/com/sprint5team/monew/base/util/NotificationTasklet.java
  src/main/java/com/sprint5team/monew/domain/notification/batch/NotificationDeleteBatchConfig.java
  src/main/java/com/sprint5team/monew/domain/notification/batch/NotificationDeleteScheduler.java
  src/main/java/com/sprint5team/monew/domain/notification/batch/NotificationDeleteTasklet.java
  src/main/java/com/sprint5team/monew/domain/notification/controller/NotificationApi.java
  src/main/java/com/sprint5team/monew/domain/notification/controller/NotificationController.java
  src/main/java/com/sprint5team/monew/domain/notification/dto/CursorPageResponseNotificationDto.java
  src/main/java/com/sprint5team/monew/domain/notification/entity/Notification.java
  src/main/java/com/sprint5team/monew/domain/notification/entity/ResourceType.java
  src/main/java/com/sprint5team/monew/domain/notification/exception/InvalidRequestParameterException.java
  src/main/java/com/sprint5team/monew/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/sprint5team/monew/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationScheduler.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationService.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationServiceImpl.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationIntegrationTest.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationSchedulerIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/notification/NotificationServiceTest.java
Labels: Refactor

#122 [Refactor/interest test] 관심사 테스트 수정
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestServiceImpl.java
  src/test/java/com/sprint5team/monew/controller/interest/InterestControllerTest.java
  src/test/java/com/sprint5team/monew/integration/interest/InterestIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/interest/InterestRepositoryCustomTest.java
  src/test/java/com/sprint5team/monew/service/interest/InterestServiceTest.java
Labels: Refactor

#123 [Refactor/comment] 댓글 좋아요 메서드 리팩터링(레이어 의존성 분리)
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/comment/util/CommentLikedEvent.java
  src/main/java/com/sprint5team/monew/domain/comment/util/CommentLikedEventListener.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
Labels: Refactor

#126 [Refactor/article] 뉴스 기사 전체적인 리팩토링
  src/main/java/com/sprint5team/monew/base/aop/MetricAspect.java
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleApi.java
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleController.java
  src/main/java/com/sprint5team/monew/domain/article/entity/Article.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCustomRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleService.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleConsumer.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleQueueManager.java
  src/main/java/com/sprint5team/monew/domain/article/util/KeywordConsumer.java
  src/main/java/com/sprint5team/monew/domain/article/util/KeywordQueueManager.java
  src/main/resources/logback-spring.xml
  src/test/java/com/sprint5team/monew/controller/article/ArticleControllerTest.java
  src/test/java/com/sprint5team/monew/integration/article/ArticleS3StorageIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/article/ArticleRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/article/ArticleServiceTest.java
Labels: Refactor

#128 [Refactor/comment] 댓글 수정시 UserId 확인하도록 변경
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
Labels: Refactor

#129 [Bugfix/article] 뉴스 기사 목록 조회 댓글 수 정렬
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCustomRepositoryImpl.java
Labels: Bug

#130 [Dev0.2] 리팩토링 결과 반영
  src/main/java/com/sprint5team/monew/base/aop/MetricAspect.java
  src/main/java/com/sprint5team/monew/base/util/NotificationTasklet.java
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleApi.java
  src/main/java/com/sprint5team/monew/domain/article/controller/ArticleController.java
  src/main/java/com/sprint5team/monew/domain/article/entity/Article.java
  src/main/java/com/sprint5team/monew/domain/article/repository/ArticleCustomRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleService.java
  src/main/java/com/sprint5team/monew/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleConsumer.java
  src/main/java/com/sprint5team/monew/domain/article/util/ArticleQueueManager.java
  src/main/java/com/sprint5team/monew/domain/article/util/KeywordConsumer.java
  src/main/java/com/sprint5team/monew/domain/article/util/KeywordQueueManager.java
  src/main/java/com/sprint5team/monew/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/comment/util/CommentLikedEvent.java
  src/main/java/com/sprint5team/monew/domain/comment/util/CommentLikedEventListener.java
  src/main/java/com/sprint5team/monew/domain/interest/service/InterestServiceImpl.java
  src/main/java/com/sprint5team/monew/domain/notification/batch/NotificationDeleteBatchConfig.java
  src/main/java/com/sprint5team/monew/domain/notification/batch/NotificationDeleteScheduler.java
  src/main/java/com/sprint5team/monew/domain/notification/batch/NotificationDeleteTasklet.java
  src/main/java/com/sprint5team/monew/domain/notification/controller/NotificationApi.java
  src/main/java/com/sprint5team/monew/domain/notification/controller/NotificationController.java
  src/main/java/com/sprint5team/monew/domain/notification/dto/CursorPageResponseNotificationDto.java
  src/main/java/com/sprint5team/monew/domain/notification/entity/Notification.java
  src/main/java/com/sprint5team/monew/domain/notification/entity/ResourceType.java
  src/main/java/com/sprint5team/monew/domain/notification/exception/InvalidRequestParameterException.java
  src/main/java/com/sprint5team/monew/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/sprint5team/monew/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/sprint5team/monew/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationScheduler.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationService.java
  src/main/java/com/sprint5team/monew/domain/notification/service/NotificationServiceImpl.java
  src/main/resources/logback-spring.xml
  src/test/java/com/sprint5team/monew/controller/article/ArticleControllerTest.java
  src/test/java/com/sprint5team/monew/controller/interest/InterestControllerTest.java
  src/test/java/com/sprint5team/monew/integration/article/ArticleS3StorageIntegrationTest.java
  src/test/java/com/sprint5team/monew/integration/interest/InterestIntegrationTest.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationIntegrationTest.java
  src/test/java/com/sprint5team/monew/integration/notification/NotificationSchedulerIntegrationTest.java
  src/test/java/com/sprint5team/monew/repository/article/ArticleRepositoryTest.java
  src/test/java/com/sprint5team/monew/repository/interest/InterestRepositoryCustomTest.java
  src/test/java/com/sprint5team/monew/repository/notification/NotificationRepositoryTest.java
  src/test/java/com/sprint5team/monew/service/article/ArticleServiceTest.java
  src/test/java/com/sprint5team/monew/service/comment/CommentServiceTest.java
  src/test/java/com/sprint5team/monew/service/interest/InterestServiceTest.java
  src/test/java/com/sprint5team/monew/service/notification/NotificationServiceTest.java
Labels: Refactor
